### ISSUE TITLE
Duplicate 'create...' methods are generated in ObjectFactory

### ISSUE THREAD

**Issue by vadimevf** [dmak/jaxb-xew-plugin#39]
Hi!

Processing of the following schema fragment produces duplicate createDemoXewBugActionItem() method in the ObjectFactory class:

    <xs:element name="DemoXewBug">
      <xs:complexType>
        <xs:sequence>
          <xs:element name="Action">
            <xs:complexType>
              <xs:choice>
                <xs:element name="UpdateSomeItems">
                  <xs:complexType>
                    <xs:sequence>
                      <xs:element name="Item" minOccurs="0" maxOccurs="unbounded">
                        <xs:complexType>
                          <xs:all>
                            <xs:element name="Key" type="xs:string"/>
                            <xs:element name="Value" type="xs:string"/>
                          </xs:all>
                        </xs:complexType>
                      </xs:element>
                    </xs:sequence>
                  </xs:complexType>
                </xs:element>
                <xs:element name="UpdateOtherItems">
                  <xs:complexType>
                    <xs:sequence>
                      <xs:element name="Item" minOccurs="0" maxOccurs="unbounded">
                        <xs:complexType>
                          <xs:all>
                            <xs:element name="Key" type="xs:string"/>
                            <xs:element name="Value" type="xs:string"/>
                          </xs:all>
                        </xs:complexType>
                      </xs:element>
                    </xs:sequence>
                  </xs:complexType>
                </xs:element>
              </xs:choice>
            </xs:complexType>
          </xs:element>
        </xs:sequence>
      </xs:complexType>
    </xs:element>

I think that happens because XmlElementWrapperPlugin.renameFactoryMethod does not check for existence of the new method prior to renaming.

**Comment by dmak** [comment]
Thanks for reporting the issue. The problem is even not in `ObjectFactory`: formally `UpdateSomeItems → Item` and `UpdateOtherItems → Item` may be completely different elements. Is it the case in reality for you? If not (as workaround) you could optimize your schema by extracting `<Item>` as separate element and using a reference to it in `xs:sequence`.

The solution in this particular case would be that one of the classes will be renamed, namely there will be two classes in the model: `DemoXewBug.Action.Item` and `DemoXewBug.Action.Item1` (for example). If you have any ideas how to resolve name collision more nicely, you're welcome to suggest.

**Comment by dmak** [comment]
I have uploaded [jaxb-xew-plugin-1.5-SNAPSHOT.jar](https://oss.sonatype.org/content/repositories/snapshots/com/github/jaxb-xew-plugin/jaxb-xew-plugin/1.5-SNAPSHOT/jaxb-xew-plugin-1.5-20150309.171455-2.jar) that should help with this issue. In particular, it appends the parent class name if there is a class name collision (e.g. `UpdateOtherItemsItem`).
