### ISSUE TITLE
Unwrapped ListWrapper inside *PortType

### ISSUE THREAD

**Issue by jmattheis** [dmak/jaxb-xew-plugin#46]
Some time ago, I asked a question on Stackoverflow, there someone said to me that ```Do you want UserManagementPortType.getAllUsers to directly return a List<User> instead? That might not be possible```, Could you verify this, that it is not possible to return a ``List<X>`` or have a ``List<X>`` inside the ``*PortType`` methode's. 
Currently I have this jaxws binding which put the request and response in an extra object
```
<jaxws:bindings xmlns:xs="http://www.w3.org/2001/XMLSchema"
            xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
            xmlns:jaxws="http://java.sun.com/xml/ns/jaxws"
            xmlns:jaxb="http://java.sun.com/xml/ns/jaxb">
    <jaxws:enableWrapperStyle>false</jaxws:enableWrapperStyle>
</jaxws:bindings>
```
With this, it works, but in does not look very nice inside the code.
http://stackoverflow.com/questions/33667462/cxf-wsdl2java-listwrapper-in-wsdl-should-be-unwrapped#comment55540572_33887005

**Comment by dmak** [comment]
Unfortunately what it comes to JAX-WS generated artefacts, there are difficulties. JAX-WS executes JAXB compilation for XSD types in isolation. That means: when JAXB model is built from XSD, JAXB plugin does not "see" that the given type is referred from JAX-WS endpoint interface (`*Port`). Basically, JAX-WS artefacts stay apart from JAXB types and to access them one need to implement JAX-WS plugin (in contrast to JAXB plugin), but I haven't heard that JAX-WS supports plugins.

Supporting of arrays (e.g. `String[]`) instead of collections (e.g. `List<String>`) is a nice-to-have feature for Xew, but it will not help you, since this array cannot be applied to endpoint interface.

However as StackOverflow answer says, `enableWrapperStyle=true` is a right way to go. I have committed the changes to [the sample](https://github.com/dmak/jaxb-xew-plugin/tree/master/samples/jaxws-maven-plugin-exclude/src/main/wsdl), which generates the endpoint interface line this:
```
@WebMethod
@WebResult(name = "item", targetNamespace = "http://jax-ws-commons.jvnet.org/test")
@RequestWrapper(localName = "list", targetNamespace = "http://jax-ws-commons.jvnet.org/test", className = "org.jvnet.jax_ws_commons.test.List")
@ResponseWrapper(localName = "listResponse", targetNamespace = "http://jax-ws-commons.jvnet.org/test", className = "org.jvnet.jax_ws_commons.test.ListResponse")
public List<String> list(
    @WebParam(name = "amount", targetNamespace = "http://jax-ws-commons.jvnet.org/test")
    BigInteger amount,
    @WebParam(name = "good", targetNamespace = "http://jax-ws-commons.jvnet.org/test")
    List<String> good,
    @WebParam(name = "urgent", targetNamespace = "http://jax-ws-commons.jvnet.org/test")
    boolean urgent);
```
Also refer [this](http://stackoverflow.com/a/9955185/267197) post concerning which types are eligible for "unwrapping".
